#ifndef FACTORYOBJECT_GLOBAL_H
#define FACTORYOBJECT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FACTORYOBJECT_LIBRARY)
#  define FACTORYOBJECT_EXPORT Q_DECL_EXPORT
#else
#  define FACTORYOBJECT_EXPORT Q_DECL_IMPORT
#endif

#endif // FACTORYOBJECT_GLOBAL_H
